### ISSUE TITLE
v0.4.1 currently broken :-(

### ISSUE THREAD

**Issue by Vangelis66** [Procyon-b/GitHub-sort-by-recently#1]
Hi 😄 ; many thanks for this very useful userscript, which I had been happily using for several months 👍 ; most sadly, as of a few days (?) ago, it is partially broken, specifically in the `Issues` and `Pull requests` tabs 😢 : 

![breakage](https://user-images.githubusercontent.com/9669492/80550833-08aa5080-89ca-11ea-9dd0-05d97719f794.jpg)

Please kindly investigate the possibility of a fix! 
Many thanks in advance! 

Best wishes (and stay safe during these difficult pandemic times...)

**Comment by Procyon-b** [comment]
Thanks for the support.   :)
It's difficult to know how many users have downloaded this userscript. At least I know now that at least another person is using it.  

That's a new problem. I was still clicking (r) a few hours ago.
I'll look into this as soon as possible.

**Comment by Procyon-b** [comment]
Fixed.  :)

It was simpler then expected.
Reload/refresh you userscript to load the new version.
Tell me if it doesn't work as expected.

**Comment by Procyon-b** [comment]
Can I ask you how you found this userscript?
I'm always curious. People can come from my programming page, but they must know me beforehand.
Some of my usescripts, userstyles are available from userstyles.org and/or greasyfork.org, and my extensions can be found with a search on the chrome web store. But this one is only stored in this repository.

**Comment by Vangelis66** [comment]
@Procyon-b wrote: 

> Reload/refresh you userscript to load the new version.
> Tell me if it doesn't work as expected.

Many thanks indeed for the instantaneous fix! It is highly appreciated! 🥇 
It is working brilliantly! 

FWIW, I'm not using **Tampermonkey** as my userscript manager, but the XUL extension **[Greasemonkey for Pale Moon](https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.31.4Fork)** installed on a fork (**New Moon**) of the _Pale Moon_ browser that is able (the fork) to run on _Windows Vista_ (the OS of my old but cherished laptop!); your script can be installed in GM via the following direct link: 

https://raw.githubusercontent.com/Procyon-b/GitHub-sort-by-recently/master/userscript.js##.user.js

On Chromium derivatives, I'm also not using Tampermonkey, but the **open-source** extension **ViolentMonkey**; your script installs and works fine there, too 👍  (so perhaps you can amend accordingly the directions in your main `README.md` file...). 

> Can I ask you how you found this userscript? I'm always curious. 
> People can come from my programming page, but they must know me beforehand.
> Some of my usescripts, userstyles are available from userstyles.org and/or greasyfork.org, 
> and my extensions can be found with a search on the chrome web store. 
> But this one is only stored in this repository.

... I am already a user of your other userscript, https://github.com/Procyon-b/make-gis-great-again, and, like you, I'm also a very curious individual - it is a habit of mine to search for other **gems** present in coders' repositories, one never knows when one may come across something really useful one never knew even existed... 

Best regards, milles merci! 👍

**Comment by Procyon-b** [comment]
> Many thanks indeed for the instantaneous fix! It is highly appreciated! 
> It is working brilliantly!

Sometimes it's a mess to try to match a new html layout; but here they only replaced a single tag (as far as the nav-bar is concerned).

> the XUL extension **[Greasemonkey for Pale Moon](https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.31.4Fork)** installed on a fork (**New Moon**) of the _Pale Moon_ browser that is able (the fork)

I heard about Pale Moon a while ago.

> to run on _Windows Vista_ (the OS of my old but cherished laptop!); 

I'm myself sticking to win7 on an old laptop (a computer I recovered almost 2 years ago). It's more "lightweight" than win8 or win10 (I think it won't even run on this laptop).

> On Chromium derivatives, I'm also not using Tampermonkey, but the **open-source** extension **ViolentMonkey**; your script installs and works fine there, too  (so perhaps you can amend accordingly the directions in your main `README.md` file...).

I'll mention other script managers. I'm also planning to create another filename for the userscript. One with `.user.js` extension, which loads automatically (at least in TM). If only I had thought about that when the repository was created.

> > Can I ask you how you found this userscript? I'm always curious.
> 
> ... I am already a user of your other userscript, https://github.com/Procyon-b/make-gis-great-again, and, like you,

Note that it's a fork. It seems that I have more freetime to fix issues than the original author.

> I'm also a very curious individual - it is a habit of mine to search for other **gems** present in coders' repositories, one never knows when one may come across something really useful one never knew even existed...

I came to github following a link for the source code of an extension. And then, met people and heard about their projects.

> Best regards, milles merci!

Il n'y a pas de quoi...
(do you speak french ?)

**Comment by Vangelis66** [comment]
> I'll mention other script managers

... Thanks!

> I'm also planning to create another filename for the userscript. 
> One with .user.js extension, which loads automatically (at least in TM).

That would be a wise move, IMHO; 99% of userscript managers, be it in the legacy/XUL or WebExtension format, have native support for the `user.js` extension!

> Note that it's a fork.

I am well aware!

> It seems that I have more freetime to fix issues than the original author.

... and many thanks for that!

... As for the OT stuff... 

> Il n'y a pas de quoi...
> (do you speak french ?)

My native tongue is Greek but I'm quite fluent in spoken/written English, which I consider as my second "tongue"; however, my late mother, God rest her soul, was born in France to Greek immigrant parents and, thus, was bilingual; a trait she was keen on passing on to her children! I did study French for four years during high school plus an additional two years in Uni, so I have a rather good comprehension of written French plus a good grasp of spoken French when it's well articulated and not spoken very quickly; sadly over the years, especially after my mom's untimely demise, I had less opportunities to practice French (and the _de facto_ language used on line is English), as a result I have practically lost the ability to write in French; I am still able to conduct basic conversations in French, but I sadly can no more claim that I "speak" the language... 

Best greetings

**Comment by Procyon-b** [comment]
> > I'll mention other script managers
> 
> ... Thanks!

Done

> > I'm also planning to create another filename for the userscript.
> > One with .user.js extension, which loads automatically (at least in TM).
> 
> That would be a wise move, IMHO; 99% of userscript managers, be it in the legacy/XUL or WebExtension format, have native support for the `user.js` extension!

I have created a copy of the userscript with another name. I have also update the readme with a clear method of installation.

> > It seems that I have more freetime to fix issues than the original author.
> 
> ... and many thanks for that!

I find that extension/userscript very useful. I wanted to keep it running.
 
> ... As for the OT stuff...
> 
> > Il n'y a pas de quoi...
> > (do you speak french ?)
> 
> My native tongue is Greek but I'm quite fluent in spoken/written English, which I consider as my second "tongue";

English is also my second language. I don't speak it as often as I would like (my brain needs at least 5min before being confortable). It's because I tend to pay too much attention to my pronunciation/accent. And the speed at which you construct your sentence while writing is not the same when you speak.  :)
I have no problem watching TV/news/series/movies. For the most part, as long as the accent is not too weird like welsh or scottish or texan. But even then...

> however, my late mother, God rest her soul, was born in France to Greek immigrant parents and, thus, was bilingual; a trait she was keen on passing on to her children! I did study French for four years during high school plus an additional two years in Uni [...]  I am still able to conduct basic conversations in French, but I sadly can no more claim that I "speak" the language...

French is my mother tongue. Unfortunately I'm not fluent in the second language of my country (dutch), and not at all in the third (german, for a very small minority)

**Comment by Vangelis66** [comment]
> I came to github following a link for the source code of an extension. And then, met people and **heard about their projects**.

... As a closing note and in case you're not already aware, there exists a superb project for (heavy) GitHub users/members called "**Refined GitHub**" hosted, where else, on [GitHub](https://github.com/sindresorhus/refined-github) itself! 
It comes in the form of a WebExtension add-on, available for **Chrome** in the [CWS](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) as well as for **Firefox** (Quantum), available in [AMO](https://addons.mozilla.org/en-US/firefox/addon/refined-github-/).

One of the vast plethora of its features _replicates behaviour implemented by your userscript in question_, the `sort-issues-by-update-time` one: 
> **Changes the default sort order of discussions to Recently updated.** => [Source Code](https://github.com/sindresorhus/refined-github/blob/master/source/features/sort-issues-by-update-time.tsx)

All the best, Vangelis

**Comment by Procyon-b** [comment]
I'm not sure knowing about this one, but I remember looking for a way to set a sorting defaut, and found a whole lib/extension in search results.
It was too many modifications in one package while I only need a few.
